# Generated by Django 6.0.6 on 2026-06-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('release_date', models.DateField()),
                ('lte_exists', models.BooleanField(default=False)),
            ],
        ),
    ]
